name: Refresh dist files (unsafe)

on:
  pull_request:
    types: [labeled]

env:
  PR_URL_FILE: pr/url.txt
  REFRESH_DIST_PATCH_FILE: pr/refresh_dist.patch

jobs:
  refresh:
    if: contains(github.event.pull_request.labels.*.name, 'refresh dist')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: changed-package-json
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/package.json
            **/package-lock.json

      - id: changed-features
        uses: tj-actions/changed-files@v44
        with:
          files: |
            features/**/*.yml
            features/**/*.yml.dist

      - uses: actions/setup-node@v4
        if: steps.changed-package-json.outputs.any_changed == 'true' || steps.changed-features.outputs.any_changed == 'true'

      - run: npm install
        if: steps.changed-package-json.outputs.any_changed == 'true' || steps.changed-features.outputs.any_changed == 'true'

      - name: Refresh dist files for feature changes
        if: steps.changed-package-json.outputs.any_changed == 'false' && steps.changed-features.outputs.any_changed == 'true'
        env:
          CHANGED_FEATURES: ${{ steps.changed-features.outputs.all_changed_files }}
        run: |
          npm run dist -- ${CHANGED_FEATURES}

      - name: Refresh all dist files (for package*.json changes)
        if: steps.changed-package-json.outputs.any_changed == 'true'
        run: |
          npm run dist

      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      - name: Save patch and PR URL
        env:
          PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
        run: |
          mkdir -p ./pr
          git diff --patch > ${{ env.REFRESH_DIST_PATCH_FILE }}
          echo $PR_URL > ${{ env.PR_URL_FILE }}

      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: |
            ${{ env.REFRESH_DIST_PATCH_FILE }}
            ${{ env.PR_URL_FILE }}
